version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/munecting
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
