name: munecting CI/CD

on:
  push:
    branches: [ "munecting" ]
  pull_request:
    branches: [ "munecting" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run : mkdir ./src/main/resources
      - run : touch ./src/main/resources/application.yml
      - run : echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      - run : cat ./src/main/resources/application.yml
    
      # gradlew에 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # gradlew 빌드
      - name: Build with Gradle
        run: ./gradlew clean build  --exclude-task test
  
    # 빌드를 성공하면 해당 프로젝트를 zip로 만듬
      # 이름은 run 에서 설정 가능
      - name: Make zip file
        run: zip -r ./munecting_1.zip .
        shell: bash
  
    #2
    # AWS 계정 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
        # 깃허브 Secret에 넣어둔 Access key
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # 깃허브 Secret에 넣어둔 Secret key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # 깃허브 Secret에 넣어둔 Region
          aws-region: ${{ secrets.AWS_REGION }}
  
    #3
    # 만들어 놓은 S3에 해당 zip 파일 저장
      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./munecting_1.zip s3://${{ secrets.AWS_S3_BUCKET }}/munecting_1.zip
      
      #4
      # AWS CodeDeploy에 배포
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name munecting-code-deploy \
          --deployment-group-name munecting-server \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=munecting_1.zip \
          --region ${{ secrets.AWS_REGION }}
