name: munecting CI/CD

on:
  push:
    branches: [ "munecting" ]
  pull_request:
    branches: [ "munecting" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run : mkdir ./src/main/resources
      - run : touch ./src/main/resources/application.yml
      - run : echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      - run : cat ./src/main/resources/application.yml
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Build
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test
        
      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy
  
      # Jar 파일 Copy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/
  
      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r -qq -j ./$GITHUB_SHA.zip ./deploy
  
      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ${{ secrets.AWS_REGION }} \
          --acl private \./$GITHUB_SHA.zip s3://${{ secrets.AWS_S3_BUCKET }}/
      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name munecting-code-deploy \
          --deployment-group-name munecting-server \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=$GITHUB_SHA.zip \
          --region ${{ secrets.AWS_REGION }}
          
      # uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      # with:
        # arguments: build
